# Generated by Django 4.2.4 on 2023-09-04 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=100)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=300)),
                ('estado', models.BooleanField(db_column='estado', default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'db_table': 'task',
                'managed': True,
            },
        ),
    ]
